using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Gekimini.Avalonia.Generator;

[Generator]
public class BuildInfoGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. 获取编译选项（用于确定 Configuration）
        var compilationOptions = context.CompilationProvider.Select(static (x, _) => x.Options);

        // 2. 结合编译触发生成逻辑
        context.RegisterSourceOutput(compilationOptions, (spc, options) =>
        {
            // 获取当前时间
            var buildTime = DateTime.Now.ToString("yyyy/M/dd H:mm:ss.fff");

            // 构建源代码字符串
            var sourceCode = $@"// <auto-generated/>
using System;

namespace Gekimini.Avalonia;

internal static class BuildInfo
{{
    public const string BuildTime = ""{buildTime}"";
}}";

            // 将代码添加到项目中
            spc.AddSource("GekiminiAvalonia_BuildInfo.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
        });
    }
}