<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <AssemblyName>Avalonia.Controls.ToolBar</AssemblyName>
        <RootNamespace></RootNamespace>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="Themes\**" />
    </ItemGroup>
</Project>
